language: c++

compiler:
  - clang
  - gcc

sudo: required
dist: trusty
addons:
  apt:
    packages:
      - protobuf-compiler
      - protobuf-c-compiler
      - libprotobuf-dev
      - libarchive-dev
      - qt5-default

install:
  - git clone https://github.com/jbeder/yaml-cpp.git yaml
  - pushd yaml
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON .
  - make -j2
  - sudo make install
  - sudo install -Dm644 yaml-cpp-config.cmake /usr/lib/cmake/yaml-cpp/yaml-cpp-config.cmake
  - sudo install -Dm644 yaml-cpp-config-version.cmake /usr/lib/cmake/yaml-cpp/yaml-cpp-config-version.cmake
  - sudo install -Dm644 yaml-cpp-targets.cmake /usr/lib/cmake/yaml-cpp/yaml-cpp-targets.cmake
  - popd

script:
  - cmake .
  - make -j2
